apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AcAvinash/blue-greenDeployment.git
    targetRevision: HEAD
    path: k8s-configs/deployment.yaml  # <--- Yeh folder path hai jahan manifests hain
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-namespace
  syncPolicy:
    automated:
      prune: true      # Purane resources delete karne ke liye
      selfHeal: true   # Agar cluster mein koi manual change kare toh wapas theek karne ke liye