apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-app-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AcAvinash/blue-greenDeployment.git
    targetRevision: HEAD
    path: k8s-configs/canary.yaml  # Folder path jahan canary.yaml rakha hai
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true