apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-blue
  labels:
    deployment-type: canary
spec:
  replicas: 1 # 80%
  selector:
    matchLabels:
      app: my-web-canary  # Different app name
      version: blue
  template:
    metadata:
      labels:
        app: my-web-canary  # Different
        version: blue
        deployment-type: canary
    spec:
      containers:
      - name: hello-container
        image: acavinash/blue:v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-green
  labels:
    deployment-type: canary
spec:
  replicas: 1 # 20% canary
  selector:
    matchLabels:
      app: my-web-canary  # Different
      version: green
  template:
    metadata:
      labels:
        app: my-web-canary  # Different
        version: green
        deployment-type: canary
    spec:
      containers:
      - name: hello-container
        image: acavinash/green:v1
---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
  labels:
    deployment-type: canary
spec:
  type: LoadBalancer
  selector:
    app: my-web-canary  # Different
    # NO version selector - canary uses replica-based split
  ports:
    - port: 81  # Different port
      targetPort: 80