# --- BLUE VERSION (V1) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
      version: blue
  template:
    metadata:
      labels:
        app: my-web
        version: blue
    spec:
      containers:
      - name: hello-container
        image: acavinash/blue:v1
        ports:
        - containerPort: 80

---
# --- GREEN VERSION (V2) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
      version: green
  template:
    metadata:
      labels:
        app: my-web
        version: green
    spec:
      containers:
      - name: hello-container
        image: acavinash/green:v1
        ports:
        - containerPort: 80

---
# --- TRAFFIC MANAGER (SERVICE) ---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    app: my-web
    # Blue-Green ke liye niche wali line uncomment rakho
    # Canary ke liye niche wali line ko delete ya comment (#) kar do
    version: blue  
  ports:
    - port: 80
      targetPort: 80